### PR TITLE
Heated

### PR DESCRIPTION
**Pull request by adrianlu95**
Droppin' some caveman fire up in this

### CODE REVIEW

**Comment by dondi** [comment]
I may want a live rendition from you sometime :)

**Comment by adrianlu95** [comment]
I hope I did this right X(

**Comment by adrianlu95** [comment]
Dondi,
Oh my goodness, I completely have misread the submission guidelines of
everything so far. First I put the paper into the bazaar repo, because I
thought that was what we were supposed to do. Second, I had thought that we
would be using the bazaar repo as our submission method. I'm so sorry for
this mistake. Am I going to get wrecked in the grade department for this
major blunder? I feel so stupid right now. I had the paper done on time,
and had committed it to the bazaar repo, which I can get proof of. Again I
am so sorry and just feel so terribly dumb for all these mistakes that I
should have caught.
Very sorry, Adrian Lu

**Comment by dondi** [comment]
Yes, I was guessing that there was some misunderstanding when I saw the follow-up pull request, but you beat me to it with regard to clarifying the situation **:)**

Let’s do this:
1. Maintain your *bazaar* fork for now, to document that you did do the work on time but just happened to put it in the wrong place.
2. Go ahead and do it right: commit to your private repository in the requested location, etc. etc.
3. I will grade *that* submission, but keep in mind in terms of punctuality that your actual submission time is based on what you committed to the *bazaar* fork.

That said, I would say that you will deserve some kind of ding in the follow-the-instructions department. But no, we will not make this a deal breaker.

**Comment by dondi** [comment]
Ah, here it is! OK, I remember now. Thank you for reminding me of this.

**Pull request closed without merging**
